volumes:
    langgraph-data:
        driver: local
    mysql_data:
        driver: local
    langgraph_api_data:
        driver: local

services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
        ports:
          - "6397:6397"
    
    langgraph-postgres:
        image: postgres:16
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s
    
    langgraph-api:
        image: musseai-agent
        ports:
            - "8080:8000"
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        env_file:
            - .env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - default
        volumes:
            - langgraph_api_data:/logs/
            - ./chromedriver-linux64:/chromedriver-linux64
        # Chrome运行所需的安全配置
        security_opt:
            - seccomp:unconfined
        shm_size: 2gb
        cap_add:
            - SYS_ADMIN
        
    mysql:
        image: mysql:8.0
        container_name: musseai-mysql
        restart: always
        ports:
          - "3307:3306"
        volumes:
          - mysql_data:/var/lib/mysql
          - ./src/mysql/crypto_portfolio.sql:/docker-entrypoint-initdb.d/01-crypto_portfolio.sql
          - ./src/mysql/insert_assets_cp.sql:/docker-entrypoint-initdb.d/02-insert_assets_cp.sql
          - ./src/mysql/auth.sql:/docker-entrypoint-initdb.d/03-auth.sql
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=crypto_portfolio
          - MYSQL_USER=asset_agent
          - MYSQL_PASSWORD=asset_agent_123456

networks:
  default:
    driver: bridge
