volumes:
    langgraph-data:
        driver: local
    langgraph_api_data:
        driver: local

services:
    langgraph-postgres:
        image: postgres:16
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s
    
    langgraph-api:
        image: musseai-agent
        ports:
            - "8123:8000"
        depends_on:
            langgraph-postgres:
                condition: service_healthy
        env_file:
            - .env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - default
        volumes:
            - langgraph_api_data:/logs/
            - ./chromedriver-linux64:/chromedriver-linux64
        # Chrome运行所需的安全配置
        security_opt:
            - seccomp:unconfined
        shm_size: 2gb
        cap_add:
            - SYS_ADMIN
networks:
  default:
    driver: bridge
